### PR TITLE
dep: directly use siphash lib in the source

### PR DESCRIPTION
**Pull request by beesaferoot**
This PR replaces the siphash library dependency to directly use the one saved into the codebase. The reason for this is to allow support on the browser (the npm version doesn't work on the browser :()

See library [repo](https://github.com/jedisct1/siphash-js?tab=readme-ov-file) for details.
### Pull Request checklist

Please confirm you have completed any of the necessary steps below.

- [ ] Meaningful Pull Request title and description
- [ ] Changes tested as described above
- [ ] Added appropriate documentation for the change.
- [ ] Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by dmohns — COMMENTED** [review]
I understand what is happening here, and agree to it. However, I would like to request a few changes in the process to make this more easy to understand.

Could we first add the `siphash` library to our repo without modifying it? Also, let's try to use a non-minified version.

Then in a second PR, let's start changing the `siphash` library such that we can use it in the browser.

**Comment by devjhane** [comment]
> I understand what is happening here, and agree to it. However, I would like to request a few changes in the process to make this more easy to understand.
> 
> Could we first add the `siphash` library to our repo without modifying it? Also, let's try to use a non-minified version.
> 
> Then in a second PR, let's start changing the `siphash` library such that we can use it in the browser.

Very well, I shall see to it.

**Comment by beesaferoot** [comment]
> I understand what is happening here, and agree to it. However, I would like to request a few changes in the process to make this more easy to understand.
> 
> Could we first add the `siphash` library to our repo without modifying it? Also, let's try to use a non-minified version.
> 
> Then in a second PR, let's start changing the `siphash` library such that we can use it in the browser.

Very well, I shall see to it.

**Comment by beesaferoot** [comment]
Updated and ready for review.  I will create a subsequent PR after this is merged.

**Review by dmohns — APPROVED** [review]

**Pull request merged**
